first-analysis-steps/loki-functors.md

Lesson updated, couple of typos and mistakes corrected. Also, several new useful things added.
Among them: 
- several useful functors
- note on the unit conversion (MeV->GeV)
- several new challenges which may be interesting both from the implementation and physics point of view (D0 vertex quality, kaons track quality, ...), and will avoid bored students from falling asleep
- proposal to check and understand the LoKi functors used in the stripping line itself

LoKi functors lesson updated and expanded

---

first-analysis-steps/README.md

Rather than pointing the site used for the LHCb workshop, link to the main SWC site.
Closes lhcb/starterkit#42.

Point to main Software Carpentry site.

---

first-analysis-steps/add-tupletools.md

I think the `new` has no advantage here, and might even teach the not so good habit of many ROOT tutorials to excessively use `new`.

Remove some typing when opening TBrowser

---

first-analysis-steps/davinci-grid.md

Following numerous problems from users trying to set up a ganga job using ancient DaVinci versions, a short tutorial on overcoming these issues was added.

Explained how to pick up a proper platform

---

first-analysis-steps/dataflow.md

The link was pointing to a wrong stripping line. 
Solution of #43 .

Wrong link fixed

---

first-analysis-steps/using-svn.md
second-analysis-steps/rerun-stripping.md

These were left over from SC. The python was causing the syntax highlighting not to work, and the using-svn lesson is not linked, so was not showing up.
(I have not added a link for it or deleted it, just fixed the incorrect formatting)

Fix old syntax from SC days

---

first-analysis-steps/code/decay-tree-fitter/ntuple_DTF1.py

Following on from #50 to make the DB tags match with the ones used when the MC was generated.

Update DB Tags in DTF options file

---

first-analysis-steps/code/davinci-grid/ntuple_options_grid.py

Following on from #50 to make the DB tags match with the ones used when the MC was generated.

Update DB Tags in grid options file

---

second-analysis-steps/filter-in-trees.md

I replaced CC by cc because it's the way it's written in the following of the lesson and also in the "build your own decay" lesson.

Fixed decay descriptor to match all others in repo

---

first-analysis-steps/prerequisites.md

The old link works only when connecting from the CERN network.
Replaced by the one with more explanations

Update the info on registering a laptop

---

first-analysis-steps/loki-functors.md

The Monte Carlo particle numbering scheme has a year in its reference.
I did not find any reference having no exact year specification, so just updated to the 2018, and put a more direct link.

Update to the 2018 PDG

---

first-analysis-steps/decay-tree-fitter.md

Shouldn't there actually be a word or two about the convergence of the DTF?

Updated DTF description here-and-there

---

first-analysis-steps/interactive-dst.md

In the new MC sample, the first candidate the passes the stripping line is a $$D^{* +}$$ instead of $$D^{* -}$$

Update interactive lesson

---

first-analysis-steps/loki-functors.md

There was a question today about `extend`; using `+=` is more intuitive and much more common.

Using += instead of extend to reduce confusion

---

first-analysis-steps/loki-functors.md

The `appMgr` is used above, and is already available as part of getting `cand`. This would be simpler to just reuse that, since the tool portion is the main focus.

Simpler app manager call

---

second-analysis-steps/simulation-fastsim.md
second-analysis-steps/simulation-gencuts.md

Discussing on mattermost, it was clear that the starterkit does not reference directly the more detailed documentation on some fast simulation options. For that reason, I have added a few references to these two simulation lessons, so people can find the implementation details if they want to know more.

Reference to twiki for details on some of the fast simulation options

---

second-analysis-steps/ganga-scripting.md

Multiple use of variable 'j', using variable 'jobs' which is inbuilt in ganga, etc.

Fixing inconsistencies in example helper functions

---

first-analysis-steps/physics-at-lhcb.md

The footnotes are not ordered properly, confusing the reader.

Fix footnote order

---

second-analysis-steps/analysis-automation-snakemake.md

Fixes bug discussed on Mattermost starterkit channel where the script fails with error
```
TypeError in line 5 of /.../Snakefile:
expected str, bytes or os.PathLike object, not InputFiles
```
Use str to convert the filename variables from type InputFiles/OutputFiles to str.

Fix bug in dosometing_py example script for snakemake

---

first-analysis-steps/prerequisites.md

`xeyes` is not installed on `lxplus7`, so it can not be used to test whether X11 forwarding works. `glxgears` should be installed virtually anywhere X11 is installed, so should be a more robust option, but we could choose any command using X11 available on `lxplus6` and `lxplus7`.

Fix prerequisites for `lxplus7`

---

first-analysis-steps/loki-functors.md

fixing typo in loki-functors.md

---

first-analysis-steps/davinci-grid.md

Just replaces `ntuple-options.py` with `ntuple_options.py` to be consistent with previous lesson and remainder of this lesson.

Consistent use of options filename

---

second-analysis-steps/hlt-intro.md

`latest` points to v50r0, which is the first Run 3 release and doesn't contain `TCKsh`.

Use specific Moore release for Run 2

---

first-analysis-steps/lhcb-dev.md

A while ago the URL to the nightly builds pages has changed from https://lhcb-nightlies.cern.ch to https://lhcb-nightlies.web.cern.ch
There's an automatic redirect, but it might disappear at some point.

Update URL to LHCb Nightly Summary page

---

first-analysis-steps/lhcb-dev.md

The link for lb-push is pointing to an obsolete twiki. I changed it to the replacement.

Changed link for lb-push

---

.travis.yml

No longer required. See https://github.com/lhcb/starterkit-ci/pull/1 for details.

Remove recommonmark hack

---

first-analysis-steps/analysis-productions.md

378db0b added a `turbo` option for `info.yaml` files in the Analysis Production lesson, but the one in the main lesson was missed

Add extra missing turbo option

---

first-analysis-steps/interactive-dst.md
first-analysis-steps/loki-functors.md

closes #232
Other calls to `lb-run DaVinci/v45r1` should also be checked, but this particular line needs fixing.
Alternatively this line could be changed to use `python` instead of `ipython`, but the interactive-ness of `ipython` seems like a helpful asset in this context.
I would also perhaps like to change some of the python syntax used throughout this section to conform to python 3 syntax. 
For example
```python
print tracks[0]
```
should really be
```python
print(tracks[0])
```
so new users don't get too familiar with old Python 2 syntax. perhaps that is another pull request

Fix lb-run environment issues when running with ipython

---

first-analysis-steps/files-from-grid.md

Replace all instances of `lb-run LHCbDirac` with `lb-dirac`, as the former is no longer available.

Replace lb-run LHCbDirac with lb-dirac

---

first-analysis-steps/interactive-dst.md

Very minor change to add parenthesis to the print function calls. While this effectively still uses Python 2.7, it's probably best to avoid confusion and to be in line with the parts of the guide that already use Python3 (e.g. ganga).

Prepare print statement to python3-style

---

first-analysis-steps/ganga-data.md

A little while ago the LHCbCompressedDatasets were introduced in ganga. While these objects can be used in the same way as the older LHCbDatasets, the explicit name and structure of the printout is slightly different.

Change to LHCbCompressedDataset

---

first-analysis-steps/davinci-grid.md

More of the same; spotted a few more Python2 print statements while *I think* these won't even work with the latest `ganga`.

Print statements to python3 for ganga tutorials

---

first-analysis-steps/minimal-dv-job.md

I am not sure if we show anywhere the list of allowed particle names in the decay descriptors. This PR links the PatricleTable from LHCb CondDB.

Link the ParticleTable

---

first-analysis-steps/interactive-dst.md
first-analysis-steps/loki-functors.md

A few things:
- Rename file to `explore.py`, from `first.py`.
- Expand on the idea of packed versus unpacked locations.
- Expand on how we can walk through the TES, cleaning up the `node`
method.
- Use an interactive Python prompt in the code examples.
- Add a call-out highlighting that the concepts can be used to debug any
options.

Update DST exploration lesson

---

README.md

Minimalistically addressing https://github.com/lhcb/starterkit-lessons/issues/179. The bulk remains to be done, meaning the actual usage of the glossary inside the lectures.

Add glossary link to main left-menu panel

---

self-guided-lessons/htcondor.md

Partly addresses #257.
Marked as draft as I've not tested this compiles locally on my machine and in case there are comments from others on my interpretation of the LHCb grid usage policy (and discussions on `~distributed-analysis`).

Add callout about LHCb Grid fair-use policy + HTCondor

---

first-analysis-steps/add-tupletools.md

There is apparently a recurring issue with jobs failing due to the lack of PV. Advertises a PV checker when using `TupleToolPropertime`

Add PV checker for TupleToolPropertime

---

conf.py
second-analysis-steps/managing-files-with-ganga.md

former URL: https://information-technology.web.cern.ch/services/batch returns 404 error. Another suitable URL which can be used here is used in replacement: https://batchdocs.web.cern.ch/

fix 404 error

---

first-analysis-steps/davinci-grid.md

Make it clear people need to test their jobs with one or two files before submitting many.

Callout for job testing

---

self-guided-lessons/htcondor-more-options.md

Previous version used `MaxDuration` in error.

Fix MaxRuntime attribute in HTCondor lesson

---

conf.py
first-analysis-steps/analysis-productions.md

Attempting to fix the 'broken links' which upset the build action

Attempt to fix the ci broken links

---

.github/workflows/build.yml
conf.py
first-analysis-steps/files-from-grid.md
second-analysis-steps/rerun-stripping.md
second-analysis-steps/simulation-gencuts.md
second-analysis-steps/simulation-running-gauss.md

The `lhcbsk` user is being retired and the files which were (supposed to be) there are being moved to `eos`.
The files which were supposed to be there need to be recreated
These may be found in `/eos/lhcb/wg/dpa/wp7/Run2SK`

Move lhcbsk paths to eos

---

second-analysis-steps/lb-git.md

Corresponds to https://gitlab.cern.ch/lhcb-dpa/wp7-training-and-documenation/starterkit-run3/-/merge_requests/56

Fix link to ssh_keys
