SUMMARY.md, second-analysis-steps/building-decays-part0.md, second-analysis-steps/building-decays-part1.md, second-analysis-steps/building-decays-part2.md, second-analysis-steps/building-decays.md
Places the decay building lessons in a subsection of the navigation, and makes the headings of those lesson two-tiered. Also adds a little 'introduction' for the top-level section.
=> Nicer formatting of decay building lessons

CONTRIBUTING.md, LICENSE.md, README.md, SUMMARY.md
Copied, and slightly cleaned up, from the first- and second-analysis-steps repos. Also tidied a few of the files in the root for nicer web navigation.
=> Re-add license

first-analysis-steps/davinci-grid.md
Migrate lhcb/first-analysis-steps#242 by @atrisovic
=> Remove SetupProject ganga

README.md, first-analysis-steps/dataflow.md, first-analysis-steps/prerequisites.md, first-analysis-steps/run-2-data-flow.md
a few minor corrections and improvements--probably the last edits I will make.
=> Minor changes

first-analysis-steps/asking-questions.md
Think this is a good alternative to the mailing lists, especially for the beginners.
=> A link to the mattermost added

second-analysis-steps/code/09-minimal-dv/ntuple_options.py, second-analysis-steps/filter-in-trees.md
Implemented Daniele's recommended fix as the lesson was broken. This is _just_ her recommendation. I haven't done any testing or checked the lesson for readability--I only added it as she said she was unfamiliar with git.
=> fix to "Reuse particles from a decay tree"

first-analysis-steps/minimal-dv-job.md
=> EventPreFilters added

first-analysis-steps/run-2-data-flow.md
=> Add information on different Turbo types

.gitignore, .travis.yml, SUMMARY.md, book.json
Adds a PDF download of the website to the sidebar, like is now in [lhcb/analysis-essentials](https://github.com/lhcb/analysis-essentials/).
=> Add PDF download to sidebar

.travis.yml
=> Generate PDF before the site is built

first-analysis-steps/code/minimal-dv/ntuple_options_xmlcatalog.py
=> DB tags updated in another file

first-analysis-steps/interactive-dst.md
=> set simulation mode when exploring DST

second-analysis-steps/managing-files-with-ganga.md
Changed wget link to reverse.py script. Was not working.
=> Changed wget link to reverse.py script. Was not working.

first-analysis-steps/davinci.md
Modified older versions of DaVinci #42
=> Update issue #42

first-analysis-steps/davinci-grid.md
The script provided in this lesson is not working (job always fails, to be more precise - fails to read the dataset) if several non-evident actions are not taken in advance.
So, instructions updated.
Request @lcapriot in the thread to check if this is fine for you?
Additional technical comment: since the list of LFNs is enormous (700+), for the purpose of the lesson we may comment most of them and leave only ~25 first, so that people do not have to wait several hours until job finishes.
Splitting by subjobs solves this issue, however, it is a subject of one the following lessons.
=> Running your first ganga job lesson updated

second-analysis-steps/rerun-stripping.md
Example changed to S28->S28r1; some extra explanations added.
=> Updated the restripping lesson

first-analysis-steps/prerequisites.md
Fixes #69 as WiFi has been okay for the last few years.
=> Remove ethernet cable from prerequisites

second-analysis-steps/fixing-errors.md
Here, the updated script from the previous lesson is used (from #103).
All the output logs updated.
=> Update the debugging lesson

second-analysis-steps/ganga-scripting.md, second-analysis-steps/managing-files-with-ganga.md
Fixes a bunch of broken links and removes the mention of the specific ganga version.
=> Fix broken links and remove reference to ganga version

second-analysis-steps/ganga-scripting.md, second-analysis-steps/managing-files-with-ganga.md
Added a link to the distributed analysis mattermost channel and mentioned that files on the grid must be unique.
=> Minor changes to the ganga lesson

second-analysis-steps/lb-git.md
- Clarify when to take which approach (`lb-*` or not)
- Add motivation for pushing a dev project and actually push it
- Add a callout with references for working with entire projects
- Other small tweaks
=> Update the git for LHCb lesson

second-analysis-steps/code/building-decays/02.optimized.py
There was one place where pions survived.
=> remove pions & minor improvements

second-analysis-steps/fixing-errors.md
In the callout, there was two mentions of "D*", and it treated these stars as the _italic_ formatting.
Let's try removing one of stars
=> Minor formatting improvement (?)

second-analysis-steps/code/18-switch-mass-hypo/ntuple_switchHypo.py, second-analysis-steps/filter-in-trees.md
Use DataOnDemand (same as AutomaticData according to https://twiki.cern.ch/twiki/bin/view/LHCb/ParticleSelection ) everywhere
=> Vibellee fix locations

second-analysis-steps/analysis-automation-snakemake.md
Links to raw files were still pointing to merged snakemake branch
=> Links to raw files were still pointing to merged snakemake branch

SUMMARY.md, self-guided-lessons/README.md
Please don't hesitate to help improve the text in the README file
=> Created a repository to add self-guided lessons

first-analysis-steps/eos-storage.md
Fix for an issue for creation of dir in the eos system.
=> Fix for eos-storage

first-analysis-steps/files-from-grid.md, first-analysis-steps/minimal-dv-job.md
something remaining from 2016 lessons...
=> fix a wrong link

first-analysis-steps/davinci-grid.md
In general, this lesson has quite poor grammar and has to be proofread carefully and corrected.
=> Minor typos correction

first-analysis-steps/add-tupletools.md, first-analysis-steps/bookkeeping.md, first-analysis-steps/dataflow.md, first-analysis-steps/davinci-grid.md, first-analysis-steps/davinci.md, first-analysis-steps/eos-storage.md, first-analysis-steps/interactive-dst.md, first-analysis-steps/lhcb-dev.md, first-analysis-steps/loki-functors.md, first-analysis-steps/minimal-dv-job.md, second-analysis-steps/filter-in-trees.md, second-analysis-steps/fixing-errors.md
Yep!
Also updates the Doxygen links to use consistent versions (`latest`, as the v44r6 Doxygen doesn't exist for some reason) and the latest URL scheme.
=> Bump DaVinci version, add callout on DaVinci version choice

first-analysis-steps/files-from-grid.md, first-analysis-steps/interactive-dst.md, first-analysis-steps/minimal-dv-job.md
Switeched to MCsim09 S28r1 Flagged
=> Update MC sample in first analysis steps

first-analysis-steps/split-jobs.md
Added callout about ignoremissing and maxfiles arguments of the splitter
=> add callout to split-jobs lesson

first-analysis-steps/minimal-dv-job.md
There are easier ways, but they do not always work. Please correct me if this is not the most reliable one.
=> Explained how to find DB tags for an MC production

first-analysis-steps/davinci-grid.md
According to my notes from the meeting, there is a suggestion to move to BKQuery in this lesson. 
Isn't it?
=> make use of BKQuery in "running DaVinci on the grid" ?

first-analysis-steps/code/minimal-dv/ntuple_options.py, first-analysis-steps/code/minimal-dv/ntuple_options_xmlcatalog.py, first-analysis-steps/minimal-dv-job.md
- Update the DB tags
- Fix the wrong link
=> Update the minimal DV job lesson

first-analysis-steps/davinci.md
Closes #160. Thanks to @vlisovsk for spotting the broken link.
=> Update Gaudi URLs.

first-analysis-steps/loki-functors.md
- Closes #162 (updated charge signs)
- Removed latex from the challenge box to make it look better
=> Update the LOKI lesson

first-analysis-steps/physics-at-lhcb.md
=> Add links to reconstruction documentation

first-analysis-steps/davinci-grid.md
Splitter added into the ganga script since the job doesn't work without the splitter
=> Fix davinci on the grid lesson, add splitter

first-analysis-steps/eos-storage.md
This is necessary for tomorrow's lesson.
I remove all the MassStorageFile business, to avoid confusion among teachers
=> Quick update of the EOS lesson

first-analysis-steps/lhcb-dev.md
=> Fix link to git tutorial

second-analysis-steps/hlt-intro.md
I reworked the Hlt lesson. The old one described how to run the Trigger and how to develop trigger lines. Once this is more stable for the Upgrade we could add it back. For now the lesson focuses on how to obtain trigger information from data and add it to a DecayTreeTuple.
=> Rework Hlt lesson

first-analysis-steps/README.md
Change analysis essentials link to new HSF website.
=> Fix Analysis Essentials link.

first-analysis-steps/minimal-dv-job.md
The link to the bookkeeping file was the old one from last year I should have updated it to the new one.
=> Updated bookkeeping file.

first-analysis-steps/asking-questions.md
Implements #179 .
Btw, we should decide what to do with the LHCb Q&A mentions, as the website is down since the last starterkit already.
=> Mention the LHCb glossary

first-analysis-steps/dataflow.md
Following the question from students regarding the meaning of "LDST" and other file formats, it can be useful to link the list of those.
=> Link to the list of file formats

first-analysis-steps/files-from-grid.md
Adding link to the CERN resources portal where one can find some instruction how to increase AFS quota (might be redundant soon, but I think it is still useful for now).
=> updating files-from-grid.md lesson

first-analysis-steps/asking-questions.md
(feel free to propose a better wording)
=> replace Q&A by Discourse

second-analysis-steps/simulation.md
* update to Gauss/v49r17 (latest sim09 production)
* remove CMTCONFIG setting, as LbEnv takes care of this
=> Update simulation.md to reflect most recent Gauss

first-analysis-steps/minimal-dv-job.md
=> Small clarifications to the minimal DaVinci lesson

first-analysis-steps/loki-functors.md
The LoKi lesson starts quite abrupt and I think none of the lessons before shows a LoKi functor. I hope these few introductory words make it easier.
=> Add some introduction to the loki session

conf.py, first-analysis-steps/analysis-productions.md, first-analysis-steps/lhcb-dev.md
Preview at http://rmatev.web.cern.ch/rmatev/starterkit/html/first-analysis-steps/lhcb-dev.html
Also I squashed a couple of problems in the build and updated the copyright year.
=> Revisit "Developing LHCb Software"

first-analysis-steps/asking-questions.md
=> Fixed typo

first-analysis-steps/asking-questions.md
change first line "Eventually"
=> Update asking-questions.md 1st line typo

first-analysis-steps/ganga-data.md
Add recommendation not to use EOS for the gangadir.
=> Update gangadir location

second-analysis-steps/simulation-intro.md
Also how to find the production IDs of existing samples
=> Add the Sim09 Version - Gauss Version correspondance

second-analysis-steps/analysis-automation-snakemake.md
Slightly updated the Snakemake 6+ changes. Added a little section on the typical snakemake functions (directory, temp and expand). Added an example of passing `rules.rule_name.output` as an input.
=> improvements to the snakemake lesson

second-analysis-steps/README.md, second-analysis-steps/advanced-dirac.md, second-analysis-steps/code/advanced-dirac/compare.py, second-analysis-steps/code/advanced-dirac/distro.py, second-analysis-steps/code/advanced-dirac/gangaTasks.py
Complete
- A basic lesson creating some distributions and histograms using GangaTasks looking at how units interact with each other and how to define transforms
To Do
- How to use the different available platforms (Dirac, Condor, etc)
- How to run Davinci in tasks
- Tasks needs an active Ganga session
- An introduction to splitters
=> Initial Request For Advanced Dirac

first-analysis-steps/ganga-data.md
Due to ```NewLHCbEnvironment``` the proposed changes required in order to merge the files in proper way.
=> change in the merging using hadd 

self-guided-lessons/htcondor.md
=> fix the links in htcondor

first-analysis-steps/code/davinci-grid/first-job.py, first-analysis-steps/davinci-grid.md, first-analysis-steps/davinci.md, first-analysis-steps/first-job.py, first-analysis-steps/interactive-dst.md, first-analysis-steps/lhcb-dev.md, first-analysis-steps/loki-functors.md, first-analysis-steps/minimal-dv-job.md
Updating the DaVinci version to the latest for Run 2 - v45r8. I tested up the local running and the TES exploring skripts.
=> Update DaVinci version

.github/workflows/build.yml
Related to issue https://github.com/lhcb/starterkit-lessons/issues/311
V2 of artifacts is deprecated - attempting to fix
=> WIP: Fix CI now that artifacts v2 is depreciated

first-analysis-steps/minimal-dv-job.md
Update outdated link from `Phys/master` to `Phys/run2-patches`
=> Fix outdated link

second-analysis-steps/README.md, second-analysis-steps/containers.md
I add a lesson on how to use containers to change the OS which is being used on lxplus.
I've tried to write it s.t. it can be adjusted for use with any institute's machines.
=> Add a lesson on containers

README.md, interesting-links/analysis-essentials.md
Backports the page of links from the HSF analysis essentials in the Run 3 starterkit
=> Backport HSF analysis essentials from Run 3 starterkit
